-- Seed data applied after migrations on `supabase start` and `supabase db reset`.
-- This starter app only uses Supabase Auth (no custom tables), so there is
-- nothing to seed. Add INSERT statements here if you introduce tables that
-- need default/demo rows for local development.
